import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import QueryProvider from "./QueryProvider";
import Header from "@/components/Header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <main className="flex justify-start items-start h-screen overflow-hidden bg-[white]">
          <Navbar />
          <main className="w-full overflow-y-scroll h-screen">
            <Header />
            <QueryProvider>{children}</QueryProvider>
          </main>
        </main>
      </body>
    </html>
  );
}
